require('lib/mootools').apply(GLOBAL);
require('classes/String');
require('classes/English');
require('classes/ANSI');
require('classes/Styles');
require('classes/Prompts');
require('classes/Messages');
require('classes/Base');
require('classes/Command');
require('classes/Container');
require('classes/Combat');
//Standard combat must be implented in the initialiation method of the world.
require('classes/CombatStandard');
require('classes/Item');
require('classes/Living');
require('classes/Player');
require('classes/Room');
require('classes/World');
require('classes/Conversation');
